<a href="https://colab.research.google.com/github/skycherepanya/Neoversity-Basic-Algorithms-and-Data-Structures/blob/main/Homework_1_Oleksandr_Cherepania.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Задача 1. Робота з зображеннями як з матрицями

###**Аналітичний метод**

**Дано:**
$$
M = \begin{pmatrix}
100 & 150 & 200 \\
50 & 100 & 150 \\
0 & 50 & 100
\end{pmatrix}, \quad
E = \begin{pmatrix}
20 & 30 & 40 \\
10 & 20 & 30 \\
5 & 10 & 15
\end{pmatrix}
$$

### 1. Зміна контрасту (множення на скаляр $\lambda = 0.5$)
Множимо кожен елемент матриці $M$ на $0.5$:
$$
0.5 \cdot M = \begin{pmatrix}
100 \cdot 0.5 & 150 \cdot 0.5 & 200 \cdot 0.5 \\
50 \cdot 0.5 & 100 \cdot 0.5 & 150 \cdot 0.5 \\
0 \cdot 0.5 & 50 \cdot 0.5 & 100 \cdot 0.5
\end{pmatrix} =
\begin{pmatrix}
50 & 75 & 100 \\
25 & 50 & 75 \\
0 & 25 & 50
\end{pmatrix}
$$

### 2. Корекція яскравості (додавання скаляра $c = 25$)
Додаємо 25 до кожного елемента матриці $M$:
$$
M + 25 = \begin{pmatrix}
100+25 & 150+25 & 200+25 \\
50+25 & 100+25 & 150+25 \\
0+25 & 50+25 & 100+25
\end{pmatrix} =
\begin{pmatrix}
125 & 175 & 225 \\
75 & 125 & 175 \\
25 & 75 & 125
\end{pmatrix}
$$

### 3. Змішування (Blending)
Формула: $0.8 \cdot M + 0.2 \cdot E$.
Спочатку порахуємо компоненти окремо:
$$
0.8 \cdot M = \begin{pmatrix}
80 & 120 & 160 \\
40 & 80 & 120 \\
0 & 40 & 80
\end{pmatrix}, \quad
0.2 \cdot E = \begin{pmatrix}
4 & 6 & 8 \\
2 & 4 & 6 \\
1 & 2 & 3
\end{pmatrix}
$$
Тепер додамо їх:
$$
Result = \begin{pmatrix}
80+4 & 120+6 & 160+8 \\
40+2 & 80+4 & 120+6 \\
0+1 & 40+2 & 80+3
\end{pmatrix} =
\begin{pmatrix}
84 & 126 & 168 \\
42 & 84 & 126 \\
1 & 42 & 83
\end{pmatrix}
$$

###**Код**

In [ ]:
import numpy as np

# 1. Ініціалізація матриць
M = np.array([
    [100, 150, 200],
    [50, 100, 150],
    [0, 50, 100]
])

E = np.array([
    [20, 30, 40],
    [10, 20, 30],
    [5, 10, 15]
])

print("--- Матриця M ---")
print(M)
print("\n--- Матриця ефекту E ---")
print(E)

# 2. Зміна контрасту (множення на 0.5)
contrast_M = M * 0.5
print("\n--- 1. Зміна контрасту (M * 0.5) ---")
print(contrast_M)

# 3. Корекція яскравості (додавання 25)
brightness_M = M + 25
print("\n--- 2. Корекція яскравості (M + 25) ---")
print(brightness_M)

# 4. Змішування (Blending: 0.8*M + 0.2*E)
blending_res = 0.8 * M + 0.2 * E
print("\n--- 3. Змішування (0.8*M + 0.2*E) ---")
print(blending_res)

--- Початкова матриця M ---
[[100 150 200]
 [ 50 100 150]
 [  0  50 100]]

--- Матриця ефекту E ---
[[20 30 40]
 [10 20 30]
 [ 5 10 15]]

--- 1. Зміна контрасту (M * 0.5) ---
[[ 50.  75. 100.]
 [ 25.  50.  75.]
 [  0.  25.  50.]]

--- 2. Корекція яскравості (M + 25) ---
[[125 175 225]
 [ 75 125 175]
 [ 25  75 125]]

--- 3. Змішування (0.8*M + 0.2*E) ---
[[ 84. 126. 168.]
 [ 42.  84. 126.]
 [  1.  42.  83.]]
